name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing dependencies
        run: npm ci
  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Linting Application
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Building Application
        run: npm run ng:build
  pacjage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Packaging Application
        run: npm run electron:pack
